name: cat_cuisine
description: "Track your cats' eating habits."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  curved_navigation_bar: ^1.0.6
  flutter_riverpod: ^2.5.1
  supabase_flutter: ^2.0.0
  go_router: ^14.2.1
  riverpod_annotation: ^2.3.5
  flex_color_scheme: ^7.3.1
  sqflite: ^2.3.3+1
  path: ^1.9.0
  logging: ^1.3.0
  collection: ^1.18.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  riverpod_lint: ^2.3.10
  riverpod_generator: ^2.4.0
  build_runner: ^2.4.11


flutter:
  uses-material-design: true
  assets:
  - assets/images/cats/
  - assets/food_brands.db
 
