name: cat_cuisine
description: "Track your cats' eating habits."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  curved_navigation_bar: ^1.0.6
  supabase_flutter: ^2.0.0
  go_router: ^14.2.1
  flex_color_scheme: ^7.3.1
  sqflite: ^2.3.3+1
  path: ^1.9.0
  logging: ^1.3.0
  collection: ^1.18.0
  flutter_bloc: ^9.1.0
  injectable: ^2.5.0
  get_it: ^8.0.3
  equatable: ^2.0.7
  google_fonts: ^6.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  injectable_generator: ^2.7.0
  build_runner: ^2.4.11


flutter:
  uses-material-design: true
  assets:
  - assets/cat_cuisine.db
 
